name: Publish Terminal Friction to Itch.io

on:
 push:
  branches:
  - main
 pull_request:
  branches:
  - main

# Gives the bot permission to create your release tags
permissions:
  contents: write

env:
 BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }} 
 DISCORD_WEBHOOK: ${{secrets.DISCORD_WEBHOOK}} 
 GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 IS_MAIN: ${{ contains(github.ref, 'main') }}
 PROJECT_NAME: "Terminal Friction"

jobs:
 CleanArtifacts:
  runs-on: ubuntu-latest
  steps:
  - uses: kolpav/purge-artifacts-action@v1
    with:
     token: ${{ secrets.GITHUB_TOKEN }}
     expire-in: 1hr

 Export:
  needs: CleanArtifacts
  runs-on: ubuntu-latest
  steps:
  - uses: actions/checkout@v4
  
  - name: Download + Authorize Godot
    run: |
       curl -L -o godot.zip https://github.com/godotengine/godot/releases/download/4.6.1-stable/Godot_v4.6.1-stable_linux.x86_64.zip
       unzip godot.zip
       mv Godot_v4.6.1-stable_linux.x86_64 godot
       ls
       chmod +x godot
 
  - name: Download Export Templates
    run: |
     curl -L -o export_templates.zip https://github.com/godotengine/godot/releases/download/4.6.1-stable/Godot_v4.6.1-stable_export_templates.tpz
     unzip export_templates.zip
  
  - name: Install Export Templates
    run: |
     mkdir -p ~/.local/share/godot/export_templates/4.6.1.stable
     mv ./templates/* ~/.local/share/godot/export_templates/4.6.1.stable
  
  # Tells Godot to build your Web HTML5 files
  - name: Export Project
    run: |
      mkdir -p exports
      ./godot --headless --export-release "Web" ./exports/index.html
  
  - uses: actions/upload-artifact@v4
    with:
     name: exports
     path: exports
  
 Release:
  needs: Export
  if: ${{ contains(github.ref, 'main') }}
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v4
   
    - name: Version
      id: tag_version
      uses: mathieudutour/github-tag-action@v5.6
      with:
       github_token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Verify Tag
      if: ${{ !steps.tag_version.outputs.new_tag }}
      run: exit 1
    
    - name: Download Exports
      uses: actions/download-artifact@v4
      with:
       name: exports
       path: exports
    
    - name: Zip
      run: zip -r release-${{ steps.tag_version.outputs.new_tag }}.zip exports
    
    - name: Create Github Release
      id: create_release
      uses: actions/create-release@v1
      env:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
       tag_name: ${{ steps.tag_version.outputs.new_tag }}
       release_name: Release ${{ steps.tag_version.outputs.new_tag }}
       body: ${{ steps.tag_version.outputs.changelog }}
    
    - name: Upload Release Artifact
      uses: actions/upload-release-asset@v1
      env:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
       upload_url: ${{ steps.create_release.outputs.upload_url }}
       asset_path: ./release-${{ steps.tag_version.outputs.new_tag }}.zip
       asset_name: release-${{ steps.tag_version.outputs.new_tag }}.zip
       asset_content_type: application/zip
    
    - uses: frdrwrt/write-to-file@v1.3
      with:
       filepath: ./VERSION.txt
       content: ${{ steps.tag_version.outputs.new_version }}
       mode: 0655
    
    - uses: actions/upload-artifact@v4
      with:
       name: VERSION
       path: ./VERSION.txt
 
 Publish:
  needs: Release
  if: ${{ contains(github.ref, 'main') }}
  runs-on: ubuntu-latest
  steps:
    - uses: actions/download-artifact@v4
      with:
       name: exports
       path: exports
    
    - name: Download + Authorize Butler
      run: |
       curl -L -o butler.zip https://broth.itch.ovh/butler/linux-amd64/LATEST/archive/default
       unzip butler.zip
       chmod +x butler
       ./butler -V
    
    - name: Login To Butler
      run: ./butler login
      
    # Pushes the built HTML5 game directly to your itch.io page
    - name: Push To Itch
      run: |
        ./butler push ./exports poorcoco/terminal-friction:html5
    
 Cleanup:
  needs: [Export, Release, Publish]
  runs-on: ubuntu-latest
  steps:
    - uses: geekyeggo/delete-artifact@v1
      with:
       name: VERSION